# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
