# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_limit'),
        ('teachers', '0002_auto_20170310_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(default=None)),
                ('theme', models.CharField(choices=[('#7c8cff', 'Azul'), ('#03A9F4', 'Azul Claro'), ('#ff2323', 'Vermelho'), ('#E91E63', 'Rosa'), ('#4CAF50', 'Verde'), ('#009688', 'Teal'), ('#FFEB3B', 'Amarelo'), ('#FF9800', 'Laranja'), ('#607D8B', 'Cinza')], default='#7c8cff', max_length=7)),
                ('greeting', models.CharField(choices=[('Love', 'Love'), ('Atenciosamente', 'Atenciosamente'), ('Cordialmente', 'Cordialmente'), ('Saudações', 'Saudações'), ('Regards', 'Regards'), ('Yours truly', 'Yours truly'), ('Sincerely', 'Sincerely'), ('Abraço', 'Abraço'), ('Obrigado', 'Obrigado'), ('Obrigada', 'Obrigada'), ('Obrigadx', 'Obrigadx'), ('Beijos', 'Beijos'), ('XOXO', 'XOXO'), ('Vida longa e próspera', 'Vida longa e próspera')], default='Love', max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('html', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='courses.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
    ]
