# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_s_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='s_subscribed',
            new_name='is_subscribed',
        ),
    ]
