# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_emaillist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='sent',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
