# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20170319_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='is_conversation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='theme',
            field=models.CharField(choices=[('#7c8cff', 'Azul'), ('#03A9F4', 'Azul Claro'), ('#2196F3', 'Outro Azul'), ('#ff2323', 'Vermelho'), ('#E91E63', 'Rosa'), ('#4CAF50', 'Verde'), ('#009688', 'Teal'), ('#FFEB3B', 'Amarelo'), ('#FF9800', 'Laranja'), ('#795548', 'Marrom'), ('#607D8B', 'Cinza')], default='#7c8cff', max_length=7),
        ),
    ]
