# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20170328_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='to_all',
            field=models.BooleanField(default=False),
        ),
    ]
