# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_emaillist_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
