# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20170820_0009'),
        ('teachers', '0011_auto_20170820_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='schools',
        ),
        migrations.AddField(
            model_name='teacher',
            name='cities',
            field=models.ManyToManyField(related_name='teachers', to='schools.City'),
        ),
    ]
