# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20170827_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='facebookuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_auth.FacebookUser'),
        ),
    ]
