# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20170829_1533'),
        ('teachers', '0016_emaillist_sent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, to='schools.City'),
        ),
    ]
