# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_emaillist_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='cities',
            field=models.ManyToManyField(blank=True, to='schools.City'),
        ),
    ]
