# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_auto_20170902_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='test_list',
            field=models.BooleanField(default=False),
        ),
    ]
