# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-05 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20170703_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='thumbnail',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
