# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('schools', models.ManyToManyField(blank=True, related_name='courses', to='schools.School')),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='schools.Student')),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to='teachers.Teacher')),
                ('years', models.ManyToManyField(blank=True, related_name='courses', to='schools.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.URLField(blank=True, null=True)),
                ('date', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('duration', models.TimeField()),
                ('category', models.CharField(choices=[('AU', 'Aula'), ('PP', 'Palestra de Professor'), ('PA', 'Palestra de Aluno'), ('OU', 'Outro')], default='AU', max_length=2)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.Course')),
                ('schools', models.ManyToManyField(related_name='events', to='schools.School')),
                ('students_attended', models.ManyToManyField(blank=True, related_name='events_attended', to='schools.Student')),
                ('stundets_missed', models.ManyToManyField(blank=True, related_name='events_missed', to='schools.Student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='teachers.Teacher')),
            ],
        ),
    ]
