# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20170101_0028'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='years',
            field=models.ManyToManyField(blank=True, related_name='courses', to='schools.Year'),
        ),
    ]
