# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_event_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='stundets_missed',
            new_name='students_missed',
        ),
    ]
