# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170110_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.IntegerField(choices=[(1, 'Sábado'), (2, 'Domingo')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.TimeField(default='03:00'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
    ]
