# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170130_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='months_apart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='weeks_apart',
            field=models.IntegerField(default=0),
        ),
    ]
