# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170218_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='begin',
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='months_apart',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='weeks_apart',
            field=models.IntegerField(null=True),
        ),
    ]
