# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170218_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start',
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(1972, 1, 1, 0, 0)),
        ),
    ]
