# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170218_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
