# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20170820_0009'),
        ('courses', '0009_course_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schools',
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.City'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.City'),
        ),
    ]
