# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170827_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prevent_enrollments',
            field=models.BooleanField(default=False),
        ),
    ]
