# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_auto_20170827_1801'),
        ('courses', '0012_course_prevent_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='coordinated_courses', to='teachers.Teacher'),
        ),
    ]
