# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='temp'),
            preserve_default=False,
        ),
    ]
