# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20170318_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='document_type',
            field=models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF')], default='RG', max_length=5),
        ),
    ]
