# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20170703_2114'),
        ('schools', '0004_auto_20170318_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facebook_create_url',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='facebookuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.FacebookUser'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_type',
            field=models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('RA', 'RA')], default='RG', max_length=5),
        ),
    ]
